### ISSUE TITLE
Fix typo in "FarmdData2"

### ISSUE THREAD

**Issue by kwurst** [cs-worcester-cs-348-01-fall-2023/GitKit-FarmData2#29]
In the paragraph under the "Bug Fix / Feature Implementation" heading in `CONTRIBUTING.md`, the word "FarmData2" contains an extra "d" that should be removed.

**Comment by Herve-kayo** [comment]
I would like to work on this issue!

**Comment by Herve-kayo** [comment]
I would like to work on this please!

**Comment by Herve-kayo** [comment]
I would like to work on this please!

**Comment by Herve-kayo** [comment]
close issue!
